WijnProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("select2/", include("django_select2.urls")),
    path("", include("WijnVoorraad.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WijnVoorraad/urls.py
from django.urls import path

import WijnVoorraad.views_basis
import WijnVoorraad.views_popup

from . import views

app_name = "WijnVoorraad"
urlpatterns = [
    path(
        "deelnemers/",
        WijnVoorraad.views_basis.DeelnemerListView.as_view(),
        name="deelnemerlist",
    ),
    path(
        "deelnemer/<int:pk>/",
        WijnVoorraad.views_basis.DeelnemerDetailView.as_view(),
        name="deelnemerdetail",
    ),
    path(
        "deelnemer/create/",
        WijnVoorraad.views_basis.DeelnemerCreateView.as_view(),
        name="deelnemer-create",
    ),
    path(
        "deelnemer/update/<int:pk>/",
        WijnVoorraad.views_basis.DeelnemerUpdateView.as_view(),
        name="deelnemer-update",
    ),
    path(
        "deelnemer/popupadd/",
        WijnVoorraad.views_popup.deelnemer_create_popup_view,
        name="deelnemer-popupadd",
    ),
    path(
        "deelnemers/popupadd/",
        WijnVoorraad.views_popup.deelnemers_create_popup_view,
        name="deelnemers-popupadd",
    ),
    path(
        "druivensoorten/",
        WijnVoorraad.views_basis.DruivenSoortListView.as_view(),
        name="druivensoortlist",
    ),
    path(
        "druivensoort/<int:pk>/",
        WijnVoorraad.views_basis.DruivenSoortDetailView.as_view(),
        name="druivensoortdetail",
    ),
    path(
        "druivensoort/create/",
        WijnVoorraad.views_basis.DruivenSoortCreateView.as_view(),
        name="druivensoort-create",
    ),
    path(
        "druivensoort/update/<int:pk>/",
        WijnVoorraad.views_basis.DruivenSoortUpdateView.as_view(),
        name="druivensoort-update",
    ),
    path(
        "druivensoort/popupadd/",
        WijnVoorraad.views_popup.druiven_soort_create_popup_view,
        name="druivensoort-popupadd",
    ),
    path(
        "gebruiker/<int:pk>/",
        WijnVoorraad.views_basis.GebruikerDetailView.as_view(),
        name="gebruikerdetail",
    ),
    path(
        "gebruiker/update/<int:pk>/",
        WijnVoorraad.views_basis.GebruikerUpdateView.as_view(),
        name="gebruiker-update",
    ),
    path(
        "locaties/",
        WijnVoorraad.views_basis.LocatieListView.as_view(),
        name="locatielist",
    ),
    path(
        "locatie/<int:pk>/",
        WijnVoorraad.views_basis.LocatieDetailView.as_view(),
        name="locatiedetail",
    ),
    path(
        "locatie/create/",
        WijnVoorraad.views_basis.LocatieCreateView.as_view(),
        name="locatie-create",
    ),
    path(
        "locatie/update/<int:pk>/",
        WijnVoorraad.views_basis.LocatieUpdateView.as_view(),
        name="locatie-update",
    ),
    path(
        "locatie/popupadd/",
        WijnVoorraad.views_popup.locatie_create_popup_view,
        name="locatie-popupadd",
    ),
    path("mutaties/", views.MutatieListView.as_view(), name="mutatielist"),
    path("mutaties_uit/", views.MutatieUitListView.as_view(), name="mutatielist_uit"),
    path("mutaties_in/", views.MutatieInListView.as_view(), name="mutatielist_in"),
    path("mutatie/<int:pk>/", views.MutatieDetailView.as_view(), name="mutatiedetail"),
    path(
        "mutatie/create/",
        views.MutatieCreateView.as_view(),
        name="mutatie-create",
    ),
    path(
        "mutatie/create/<int:ontvangst_id>/",
        views.MutatieCreateView.as_view(),
        name="mutatie-create",
    ),
    path(
        "mutatie/create/<int:ontvangst_id>/<int:voorraad_id>",
        views.MutatieCreateView.as_view(),
        name="mutatie-create",
    ),
    path(
        "mutatie/update/<int:pk>/",
        views.MutatieUpdateView.as_view(),
        name="mutatie-update",
    ),
    path("ontvangsten/", views.OntvangstListView.as_view(), name="ontvangstlist"),
    path(
        "ontvangst/<int:pk>/",
        views.OntvangstDetailView.as_view(),
        name="ontvangstdetail",
    ),
    path(
        "ontvangst/create", views.OntvangstCreateView.as_view(), name="ontvangst-create"
    ),
    path(
        "ontvangst/create/<int:wijn_id>/",
        views.OntvangstCreateView.as_view(),
        name="ontvangst-create",
    ),
    path(
        "ontvangst/update/<int:pk>/",
        views.OntvangstUpdateView.as_view(),
        name="ontvangst-update",
    ),
    path(
        "standaardLocatie/popupadd/",
        WijnVoorraad.views_popup.standaard_locatie_create_popup_view,
        name="standaardlocatie-popupadd",
    ),
    path(
        "vak/<int:pk>/",
        WijnVoorraad.views_basis.VakDetailView.as_view(),
        name="vakdetail",
    ),
    path(
        "vak/create/<int:locatie_id>/",
        WijnVoorraad.views_basis.VakCreateView.as_view(),
        name="vak-create",
    ),
    path(
        "vak/update/<int:pk>/",
        WijnVoorraad.views_basis.VakUpdateView.as_view(),
        name="vak-update",
    ),
    path(
        "verplaatsinvakken/<int:voorraad_id>/<int:nieuwe_locatie_id>/<int:aantal>",
        views.VoorraadVerplaatsInVakken.as_view(),
        name="verplaatsinvakken",
    ),
    path(
        "verplaatsen/<int:pk>", views.VoorraadVerplaatsen.as_view(), name="verplaatsen"
    ),
    path(
        "voorraad/<int:locatie_id>/<int:wijn_id>/<int:ontvangst_id>",
        views.VoorraadDetailView.as_view(),
        name="voorraaddetail",
    ),
    path(
        "voorraad/filter",
        views.VoorraadFilterView.as_view(),
        name="voorraadlist_filter",
    ),
    path(
        "ontvangstvoorraad/<int:ontvangst_id>/",
        views.OntvangstVoorraadView.as_view(),
        name="ontvangstvoorraad",
    ),
    path(
        "voorraadvakken/",
        views.VoorraadVakkenListView.as_view(),
        name="voorraadvakkenlist",
    ),
    path("wijnen/", views.WijnListView.as_view(), name="wijnlist"),
    path("wijn/<int:pk>/", views.WijnDetailView.as_view(), name="wijndetail"),
    path("wijn/create/", views.WijnCreateView.as_view(), name="wijn-create"),
    path("wijn/update/<int:pk>/", views.WijnUpdateView.as_view(), name="wijn-update"),
    path(
        "wijn/opzoeken/<int:pk>/", views.WijnSearchView.as_view(), name="wijn-opzoeken"
    ),
    path(
        "wijn/popupadd/",
        WijnVoorraad.views_popup.wijn_create_popup_view,
        name="wijn-popupadd",
    ),
    path(
        "wijnDruivensoorten/popupadd/",
        WijnVoorraad.views_popup.wijn_druiven_soorten_create_popup_view,
        name="wijndruivensoort-popupadd",
    ),
    path(
        "wijnsoorten/",
        WijnVoorraad.views_basis.WijnSoortListView.as_view(),
        name="wijnsoortlist",
    ),
    path(
        "wijnsoort/<int:pk>/",
        WijnVoorraad.views_basis.WijnSoortDetailView.as_view(),
        name="wijnsoortdetail",
    ),
    path(
        "wijnsoort/create/",
        WijnVoorraad.views_basis.WijnSoortCreateView.as_view(),
        name="wijnsoort-create",
    ),
    path(
        "wijnsoort/update/<int:pk>/",
        WijnVoorraad.views_basis.WijnSoortUpdateView.as_view(),
        name="wijnsoort-update",
    ),
    path(
        "wijnsoort/popupadd/",
        WijnVoorraad.views_popup.wijn_soort_create_popup_view,
        name="wijnsoort-popupadd",
    ),
    path("", views.VoorraadListView.as_view(), name="voorraadlist"),
    path("AI-zoeken/", views.AIview.as_view(), name="AI-zoeken"),
    path("bestellingen/", views.BestellingListView.as_view(), name="bestellinglist"),
    path(
        "bestelling/<int:pk>/",
        views.BestellingDetailView.as_view(),
        name="bestellingdetail",
    ),
    path(
        "bestelling/create",
        views.BestellingCreateView.as_view(),
        name="bestelling-create",
    ),
    path(
        "bestelling/update/<int:pk>/",
        views.BestellingUpdateView.as_view(),
        name="bestelling-update",
    ),
    path(
        "bestellingregelsselecteren/<int:bestelling_id>",
        views.BestellingRegelsSelecteren.as_view(),
        name="bestellingregelsselecteren",
    ),
    path(
        "bestellingregel/update/<int:pk>/",
        views.BestellingRegelUpdateView.as_view(),
        name="bestellingregel-update",
    ),
    path(
        "bestellingenverzamelen/",
        views.BestellingenVerzamelen.as_view(),
        name="bestellingenverzamelen",
    ),
    path(
        "bestellingverzamelendetail/<int:pk>/",
        views.BestellingVerzamelenDetail.as_view(),
        name="bestellingverzamelendetail",
    ),
    path(
        "bestellingregelverplaatsen/<int:pk>",
        views.BestellingRegelVerplaatsen.as_view(),
        name="bestellingregelverplaatsen",
    ),
    path(
        "bestellingregelverplaatsinvakken/<int:bestellingregel_id>/<int:nieuwe_locatie_id>/<int:aantal>",
        views.BestellingregelVerplaatsInVakken.as_view(),
        name="bestellingregelverplaatsinvakken",
    ),
    path(
        "voorraadcontroleren/",
        views.VoorraadControleren.as_view(),
        name="voorraadcontroleren",
    ),
]

WijnVoorraad/templates/WijnVoorraad/base.html
{% load i18n static %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir=ltr>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}
        {% if subtitle %}{{ subtitle }} |{% endif %}
        {{ title }} | {{ site_title|default:_('Wijnvoorraad') }}
      {% endblock %}
    </title>
    <link rel="shortcut icon" type="image/ico" href="{% static 'WijnVoorraad/img/vino_sm.ico' %}">
   
    <link rel="stylesheet" href="{% block stylesheet %}{% static "WijnVoorraad/css/eigen.css" %}{% endblock %}">
    {% block extrastyle %}{% endblock %}
    {% block extrahead %}{% endblock %}
    {% block responsive %}
      <link rel="stylesheet" href="{% static "WijnVoorraad/css/responsive.css" %}">
    {% endblock %}
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
    {% load wijnvoorraad_extras %}
  </head>
  <body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
        data-admin-utc-offset="{% now "Z" %}">
    <!-- Container -->
    <div id="container">
      {% if not is_popup %}
        <!-- Header -->
        {% block header %}
          <div id="header">
            <div id="branding">
              {% block branding %}
                <h1 id="site-name">
                  <img src="{% static 'WijnVoorraad/img/vino.png' %}" width="50" height="50" alt="logo">
                  <a href="{% url 'WijnVoorraad:voorraadlist' %}">{{ site_header|default:_('Wijnvoorraad') }}</a>
                </h1>
              {% endblock %}
            </div>
            {% block usertools %}
              <div id="user-tools">
                {% block welcome-msg %}
                  {% translate 'Welcome,' %}
                  <strong>{% firstof user.get_full_name user.get_short_name user.get_username %}</strong>.
                {% endblock %}
                {% block userlinks %}{% endblock %}
              </div>
            {% endblock %}
            {% block header_bar %}
              {% if user.id %}
                <div id="header_bar">
                  <div class="dropdownmenu">
                    <button class="dropdownmenu-button" type="submit">
                      <img src="{% static '/WijnVoorraad/img/menuicon.png' %}"
                           width="30"
                           height="30"
                           alt="Menu" />
                    </button>
                    <div class="dropdownmenu-content">
                      <a href="{% url 'WijnVoorraad:deelnemerlist' %}">Deelnemers</a>
                      <a href="{% url 'WijnVoorraad:druivensoortlist' %}">Druivensoorten</a>
                      <a href="{% url 'WijnVoorraad:wijnsoortlist' %}">Wijnsoorten</a>
                      <a href="{% url 'WijnVoorraad:locatielist' %}">Locaties</a>
                      <a href="{% url 'WijnVoorraad:wijnlist' %}">Wijnen</a>
                      <a href="{% url 'WijnVoorraad:ontvangstlist' %}">Ontvangsten</a>
                      <a href="{% url 'WijnVoorraad:mutatielist_in' %}">Inkomende mutaties</a>
                      <a href="{% url 'WijnVoorraad:mutatielist_uit' %}">Uitgaande mutaties</a>
                      <a href="{% url 'WijnVoorraad:mutatielist' %}">Alle mutaties</a>
                      <a href="{% url 'WijnVoorraad:bestellinglist' %}">Bestellingen</a>
                      <a href="{% url 'WijnVoorraad:bestellingenverzamelen' %}">Bestellingen verzamelen</a>
                      <a href="{% url 'WijnVoorraad:voorraadvakkenlist' %}">Actuele voorraad vakken</a>
                      {% if user.is_staff %}
                        <a href="{% url 'WijnVoorraad:voorraadcontroleren' %}">Voorraad controleren (Admin)</a>
                        <a href="{% url 'admin:index' %}">Beheer (Admin)</a>
                      {% endif %}
                    </div>
                  </div>
                  <a href="{% url 'WijnVoorraad:gebruikerdetail' user.id %}">
                    <img src="{% static '/WijnVoorraad/img/Accounticon.png' %}"
                         width="30"
                         height="30"
                         alt="Profiel" />
                  </a>
                </div>
              {% endif %}
            {% endblock header_bar %}
            {% block nav-global %}{% endblock %}
          </div>
        {% endblock %}
        <!-- END Header -->
        {% block breadcrumbs %}
          <div class="breadcrumbs">
            <a href="{% url 'WijnVoorraad:voorraadlist' %}">Home</a>
            {% block breadcrumbs_extra %} {% endblock %}
            {% if title %}&rsaquo; {{ title }}{% endif %}
            <div style=" float: right;">Version:  {{ 'VERSION'|setting }}</div>
          </div>
        {% endblock %}
      {% endif %}
      <!-- END Not popup -->
      <div class="main" id="main">
        <div class="content">
          {% block messages %}
            {% if messages %}
              <ul class="messagelist">
                {% for message in messages %}
                  <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
                {% endfor %}
              </ul>
            {% endif %}
          {% endblock messages %}
          <!-- Content -->
          <div id="content" class="{% block coltype %}colM{% endblock %}">
            {% block pretitle %}{% endblock %}
            {% block content_title %}
              {% if title %}<h1>{{ title }}</h1>{% endif %}
            {% endblock %}
            {% block content_subtitle %}
              {% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}
            {% endblock %}
            {% block content %}{{ content }}{% endblock %}
            
          </div>
          <!-- END Content -->
          <div id="footer">
            {% block footer %}{% endblock %}
          </div>
        </div>
      </div>
    </div>
    <!-- END Container -->
  </body>
</html>

WijnVoorraad/templates/WijnVoorraad/bestellingregels_selecteren.html
{% extends "./base.html" %}
{% load i18n static %}
{% load wijnvoorraad_extras %}

{% block breadcrumbs_extra %}
&rsaquo;<a href="{% url 'WijnVoorraad:bestellingdetail' bestelling.id %}">Bestelling</a>
{% endblock %}

{% block content %}
<div id="content-main">
  <div class="detail-block">
    <div class="detail-row">
        <label class="detail-column-label">Deelnemer</label> 
        <label class="detail-column">{{  bestelling.deelnemer.naam }}</label>
    </div>
    <div class="detail-row">
        <label class="detail-column-label">Datum aangemaakt</label>
        <label class="detail-column">{{ bestelling.datumAangemaakt }}</label>
    </div>
    <div class="detail-row">
        <label class="detail-column-label">Van locatie</label>
        <label class="detail-column">
            {{  bestelling.vanLocatie.omschrijving }}
            &nbsp;
            <a href="{% url 'WijnVoorraad:locatiedetail' bestelling.vanLocatie.id %}"
                title="Details bekijken">
                <img src="{% static 'admin/img/icon-viewlink.svg' %}" alt="Details">
            </a>
        </label>
    </div>
    <div class="detail-row">
        <label class="detail-column-label">Opmerking</label>
        <label class="detail-column">{{ bestelling.opmerking }}</label>
    </div>
  </div>  <!-- end detail-block -->
  {% include 'WijnVoorraad/component_filter.html' with show_filters=True %}
  <div>
    <form method="post">{% csrf_token %}
    <input type="hidden" name='bestelling_id' id="bestelling_id" value="{{bestelling.id}}">
    <input type="hidden" name='aantal_vrd' id="aantal_vrd" value="{{bestel_list|length}}">
    <input type="submit" name="Save" id="Save" value="Opslaan">
    <div style="overflow-x:auto;">
    <table class="wijnvoorraad">
        {% for v in bestel_list %}
        <tr class="wijnvoorraad_row {{ v.wijn.wijnsoort.style_css_class }}">
          <td class="col-18 col-s-16">
            <a href="{% url 'WijnVoorraad:voorraaddetail' v.locatie.id v.wijn.id v.ontvangst.id %}">
              <b>{{ v.wijn.volle_naam }}</b>
            </a>
          </td>
          <td class="col-2 col-s-4">
            <a href="{% url 'WijnVoorraad:voorraaddetail' v.locatie.id v.wijn.id v.ontvangst.id %}"
               tabindex="-1">#{{ v.aantal }}</a>
          </td>
          <td class="col-18 col-s-16">
            <a href="{% url 'WijnVoorraad:voorraaddetail' v.locatie.id v.wijn.id v.ontvangst.id %}"
               tabindex="-1">
              {{ v.wijn.wijnsoort.omschrijving }}
              {% if v.wijn.jaar %}, {{ v.wijn.jaar | default_if_none:"" }}{% endif %}
              {% if v.wijn.land %}, {{ v.wijn.land }}{% endif %}
              {% for d in v.wijn.wijnDruivensoorten.all %}, {{ d.omschrijving }}{% endfor %}
              {% if v.vak %}, Vak: {{ v.vak.code }}{% endif %}
            </a>
          </td>
          <td class="col-2 col-s-4">
            <input type="hidden" name='bestellingregel_id{{ forloop.counter }}' id="bestellingregel_id{{ forloop.counter }}" value="{{v.bestellingregel_id}}">
            <input type="hidden" name='voorraad_id{{ forloop.counter }}' id="voorraad_id{{ forloop.counter }}" value="{{ v.id }}">
            <input class="aantal" type="number" name='aantal_bestellen{{ forloop.counter }}' value="{{v.aantal_bestellen}}"
            min="1" max="{{ v.aantal }}" id="aantal_bestellen{{ forloop.counter }}"
            />
          </td>
        </tr>
      {% empty %}
        <p>Er is GEEN voorraad.</p>
      {% endfor %}
      </table>
    </div>
    </form>
  </div>
{% endblock %}

WijnVoorraad/templates/WijnVoorraad/wijnvoorraad_detail.html
{% extends "./base.html" %}
{% load i18n static %}
{% load wijnvoorraad_extras %}

{% block content %}
{% block content_title %}{% endblock %}
<h2>Vooraad van {{ wijn.volle_naam }}</h2>

<div id="content-main">
    <div class="content-row">
        <div class="col-6 col-s-20">
            <table class="metkader" width="100%">
                {% for v in voorraad_list %}
                    {% if v == voorraad_list|first %}
                        <thead>
                            <tr>
                                <th style="text-align: center">
                                    Vak
                                </th>
                                <th style="text-align: center">
                                    Aantal
                                </th>
                                <th>
                                </th>
                                <th>
                                </th>
                                <th>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                    {% endif %} 
                    <form method="post">{% csrf_token %}
                    <tr>
                        <td style="vertical-align: middle; text-align: center">
                            {{ v.vak.code |default:"---" }}
                        </td>
                        <td style="vertical-align: middle; text-align: center">
                            {{ v.aantal }}
                            {% if v.aantal_rsv > 0 %}
                                (-{{ v.aantal_rsv }})
                            {% endif %}
                        </td>
                        <td>
                            <input type="hidden" name='voorraad_id' id="voorraad{{ forloop.counter }}" value="{{v.id}}">
                            <input type="submit" name="Drinken" value="Drinken">
                        </td>
                        <td>
                            <input type="hidden" name='voorraad_id' id="voorraad{{ forloop.counter }}" value="{{v.id}}">
                            <input type="submit" name="Afboeken" value="Afboeken">
                        </td>
                        <td>
                            <input type="hidden" name='voorraad_id' id="voorraad{{ forloop.counter }}" value="{{v.id}}">
                            <input type="submit" name="Verplaatsen" value="Verplaatsen">
                        </td>
                    </tr>
                    </form>
                {% empty %}
                    <tbody>
                    <p>Er is geen actuele voorraad voor deze deelnemer, locatie en wijn.</p>
                {% endfor %}
                </tbody>
            </table>
        </div> <!-- end col -->
        {% if wijn.foto  %}
            <div class="col-8 col-s-11">
        {% else %}
            <div class="col-14 col-s-11">
        {% endif %}
            <div class="detail-block">
                <div class="detail-row">
                    <label class="detail-column-label">Deelnemer</label>
                    <label class="detail-column">
                        {{ ontvangst.deelnemer.naam }}
                        &nbsp;
                        <a href="{% url 'WijnVoorraad:deelnemerdetail' ontvangst.deelnemer.id %}"
                            title="Details bekijken">
                            <img src="{% static 'admin/img/icon-viewlink.svg' %}" alt="Details">
                        </a>
                    </label>
                </div>
                <div class="detail-row">
                    <label class="detail-column-label">Locatie</label>
                    <label class="detail-column">
                        {{ locatie.omschrijving }}
                        &nbsp;
                        <a href="{% url 'WijnVoorraad:locatiedetail' locatie.id %}"
                            title="Details bekijken">
                            <img src="{% static 'admin/img/icon-viewlink.svg' %}" alt="Details">
                        </a>
                    </label>
                </div>
                <div class="detail-row">
                    <label class="detail-column-label">Wijn</label>
                    <label class="detail-column">
                        {{ wijn.volle_naam }}
                        &nbsp;
                        <a href="{% url 'WijnVoorraad:wijndetail' wijn.id %}"
                            title="Details bekijken">
                            <img src="{% static 'admin/img/icon-viewlink.svg' %}" alt="Details">
                        </a>
                    </label>
                </div>
                <div class="detail-row">
                    <label class="detail-column-label">Ontvangstdatum</label>
                    <label  class="detail-column">
                        {{ ontvangst.datumOntvangst }}
                        &nbsp;
                        <a href="{% url 'WijnVoorraad:ontvangstdetail' ontvangst.id %}"
                            title="Details bekijken">
                            <img src="{% static 'admin/img/icon-viewlink.svg' %}" alt="Details">
                        </a>
                    </label>            
                </div>
                <div class="detail-row">
                    <label class="detail-column-label">Wijnsoort</label>
                    <label class="detail-column">{{ wijn.wijnsoort.omschrijving }}</label>            
                </div>
                {% if wijn.jaar %}
                    <div class="detail-row">
                        <label class="detail-column-label">Jaartal</label>
                        <label class="detail-column">{{ wijn.jaar|default_if_none:"" }}</label>            
                    </div>
                {% endif %}
                {% if wijn.land %}
                    <div class="detail-row">
                        <label class="detail-column-label">Land</label>
                        <label class="detail-column">{{ wijn.land }}</label>            
                    </div>
                {% endif %}
                {% if wijn.streek %}
                    <div class="detail-row">
                        <label class="detail-column-label">Streek</label>
                        <label class="detail-column">{{ wijn.streek }}</label>        
                    </div>
                {% endif %}
                {% if wijn.classificatie %}
                    <div class="detail-row">
                        <label class="detail-column-label">Classificatie</label>
                        <label class="detail-column">{{ wijn.classificatie }}</label>            
                    </div>
                {% endif %}
                {% if wijn.website %}
                    <div class="detail-row">
                    <label class="detail-column-label">Website</label>
                        <a class="detail-column" href="{{ wijn.website }}" target=”_blank”>
                            {{ wijn.website }}
                        </a>
                    </div>
                {% endif %}
                {% if wijn.opmerking %}
                    <div class="detail-row">
                        <label class="detail-column-label">Opmerking</label>
                        <label class="detail-column">{{ wijn.opmerking }} </label>
                    </div>
                {% endif %}
                {% if ontvangst.leverancier %}
                    <div class="detail-row">
                        <label class="detail-column-label">Leverancier</label>
                        <label class="detail-column">{{ ontvangst.leverancier }}</label>
                    </div>
                {% endif %}
                {% if ontvangst.website %}
                    <div class="detail-row">
                        <label class="detail-column-label">Website</label>
                        <a class="detail-column" href="{{ ontvangst.website }}" target=”_blank”>
                            {{ ontvangst.website }}
                        </a>
                    </div>
                {% endif %}
                {% if ontvangst.prijs %}
                    <div class="detail-row">
                        <label class="detail-column-label">Prijs</label>
                        <label class="detail-column">{{ ontvangst.prijs|default_if_none:"" }}</label>
                    </div>
                {% endif %}
                {% if ontvangst.opmerking %}
                    <div class="detail-row">
                        <label class="detail-column-label">Opmerking</label>
                        <label class="detail-column">{{ ontvangst.opmerking }}</label>
                    </div>
                {% endif %}
                {% if wijn.wijnDruivensoorten.all.count >= 1 %}
                    <div class="detail-row">
                        <label class="detail-column-label">Druivensoorten</label>
                        {% for d in wijn.wijnDruivensoorten.all %}
                            {% if d == wijn.wijnDruivensoorten.all|first %} 
                                <label class="detail-column">{{ d.omschrijving }}
                            {% else %}
                                , {{ d.omschrijving }}
                            {% endif %}
                            &nbsp;
                            <a href="{% url 'WijnVoorraad:druivensoortdetail' d.id %}"
                                title="Details bekijken">
                                <img src="{% static 'admin/img/icon-viewlink.svg' %}" alt="Details">
                            </a>
                            {% endfor %}
                        </label>
                    </div>
                {% endif %}
            </div>  <!-- end detail-block -->
        </div> <!-- end col -->
        {% if wijn.foto  %}
            <div class="col-6 col-s-9">
                <div class="detail-block">
                    <img src="{{ wijn.foto.url }}" alt="Foto" style="max-height: 300px" />
                </div>  <!-- end detail-block -->
            </div>  <!-- end col -->
        {% endif %}
    </div>   <!-- end content-row -->
</div>  <!-- end content-main -->
{% endblock %}